modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Naturally%20Charged%20Creepers"
logoFile="icon.png"

[[mods]]
modId="naturallychargedcreepers"
version="3.5"
displayName="Naturally Charged Creepers"
displayURL="https://serilum.com/mod/naturally-charged-creepers"
authors="Rick South"
description='''Allows creepers to spawn charged naturally, increasing the game's difficulty.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, kate1073, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.naturallychargedcreepers]]
    modId="collective"
    type="required"
    versionRange="[7.86,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.naturallychargedcreepers]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.2,1.21.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "naturallychargedcreepers.mixins.json"